/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouteImport } from './routes/_'
import { Route as TemplatesRouteImport } from './routes/_.templates'
import { Route as SettingsRouteImport } from './routes/_.settings'
import { Route as DecksRouteImport } from './routes/_.decks'
import { Route as DashboardRouteImport } from './routes/_.dashboard'
import { Route as AlgorithmsRouteImport } from './routes/_.algorithms'
import { Route as TemplatesTemplateIdRouteImport } from './routes/_.templates.$templateId'
import { Route as SettingsLearningRouteImport } from './routes/_.settings.learning'
import { Route as SettingsInterfaceRouteImport } from './routes/_.settings.interface'
import { Route as DecksDeckIdRouteImport } from './routes/_.decks.$deckId'
import { Route as AlgorithmsAlgorithmIdRouteImport } from './routes/_.algorithms.$algorithmId'
import { Route as DecksDeckIdDetailsRouteImport } from './routes/_.decks.$deckId.details'
import { Route as DecksDeckIdCardsRouteImport } from './routes/_.decks.$deckId.cards'

const Route = RouteImport.update({
  id: '/_',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => Route,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => Route,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => Route,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => Route,
} as any)
const AlgorithmsRoute = AlgorithmsRouteImport.update({
  id: '/algorithms',
  path: '/algorithms',
  getParentRoute: () => Route,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const SettingsLearningRoute = SettingsLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsInterfaceRoute = SettingsInterfaceRouteImport.update({
  id: '/interface',
  path: '/interface',
  getParentRoute: () => SettingsRoute,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/$deckId',
  path: '/$deckId',
  getParentRoute: () => DecksRoute,
} as any)
const AlgorithmsAlgorithmIdRoute = AlgorithmsAlgorithmIdRouteImport.update({
  id: '/$algorithmId',
  path: '/$algorithmId',
  getParentRoute: () => AlgorithmsRoute,
} as any)
const DecksDeckIdDetailsRoute = DecksDeckIdDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => DecksDeckIdRoute,
} as any)
const DecksDeckIdCardsRoute = DecksDeckIdCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => DecksDeckIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/algorithms': typeof AlgorithmsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/decks': typeof DecksRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/algorithms/$algorithmId': typeof AlgorithmsAlgorithmIdRoute
  '/decks/$deckId': typeof DecksDeckIdRouteWithChildren
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/learning': typeof SettingsLearningRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/decks/$deckId/cards': typeof DecksDeckIdCardsRoute
  '/decks/$deckId/details': typeof DecksDeckIdDetailsRoute
}
export interface FileRoutesByTo {
  '/algorithms': typeof AlgorithmsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/decks': typeof DecksRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/algorithms/$algorithmId': typeof AlgorithmsAlgorithmIdRoute
  '/decks/$deckId': typeof DecksDeckIdRouteWithChildren
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/learning': typeof SettingsLearningRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/decks/$deckId/cards': typeof DecksDeckIdCardsRoute
  '/decks/$deckId/details': typeof DecksDeckIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_': typeof RouteWithChildren
  '/_/algorithms': typeof AlgorithmsRouteWithChildren
  '/_/dashboard': typeof DashboardRoute
  '/_/decks': typeof DecksRouteWithChildren
  '/_/settings': typeof SettingsRouteWithChildren
  '/_/templates': typeof TemplatesRouteWithChildren
  '/_/algorithms/$algorithmId': typeof AlgorithmsAlgorithmIdRoute
  '/_/decks/$deckId': typeof DecksDeckIdRouteWithChildren
  '/_/settings/interface': typeof SettingsInterfaceRoute
  '/_/settings/learning': typeof SettingsLearningRoute
  '/_/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/_/decks/$deckId/cards': typeof DecksDeckIdCardsRoute
  '/_/decks/$deckId/details': typeof DecksDeckIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/algorithms'
    | '/dashboard'
    | '/decks'
    | '/settings'
    | '/templates'
    | '/algorithms/$algorithmId'
    | '/decks/$deckId'
    | '/settings/interface'
    | '/settings/learning'
    | '/templates/$templateId'
    | '/decks/$deckId/cards'
    | '/decks/$deckId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/algorithms'
    | '/dashboard'
    | '/decks'
    | '/settings'
    | '/templates'
    | '/algorithms/$algorithmId'
    | '/decks/$deckId'
    | '/settings/interface'
    | '/settings/learning'
    | '/templates/$templateId'
    | '/decks/$deckId/cards'
    | '/decks/$deckId/details'
  id:
    | '__root__'
    | '/_'
    | '/_/algorithms'
    | '/_/dashboard'
    | '/_/decks'
    | '/_/settings'
    | '/_/templates'
    | '/_/algorithms/$algorithmId'
    | '/_/decks/$deckId'
    | '/_/settings/interface'
    | '/_/settings/learning'
    | '/_/templates/$templateId'
    | '/_/decks/$deckId/cards'
    | '/_/decks/$deckId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Route: typeof RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_': {
      id: '/_'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/templates': {
      id: '/_/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof Route
    }
    '/_/settings': {
      id: '/_/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof Route
    }
    '/_/decks': {
      id: '/_/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof Route
    }
    '/_/dashboard': {
      id: '/_/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof Route
    }
    '/_/algorithms': {
      id: '/_/algorithms'
      path: '/algorithms'
      fullPath: '/algorithms'
      preLoaderRoute: typeof AlgorithmsRouteImport
      parentRoute: typeof Route
    }
    '/_/templates/$templateId': {
      id: '/_/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/_/settings/learning': {
      id: '/_/settings/learning'
      path: '/learning'
      fullPath: '/settings/learning'
      preLoaderRoute: typeof SettingsLearningRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_/settings/interface': {
      id: '/_/settings/interface'
      path: '/interface'
      fullPath: '/settings/interface'
      preLoaderRoute: typeof SettingsInterfaceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_/decks/$deckId': {
      id: '/_/decks/$deckId'
      path: '/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof DecksRoute
    }
    '/_/algorithms/$algorithmId': {
      id: '/_/algorithms/$algorithmId'
      path: '/$algorithmId'
      fullPath: '/algorithms/$algorithmId'
      preLoaderRoute: typeof AlgorithmsAlgorithmIdRouteImport
      parentRoute: typeof AlgorithmsRoute
    }
    '/_/decks/$deckId/details': {
      id: '/_/decks/$deckId/details'
      path: '/details'
      fullPath: '/decks/$deckId/details'
      preLoaderRoute: typeof DecksDeckIdDetailsRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
    '/_/decks/$deckId/cards': {
      id: '/_/decks/$deckId/cards'
      path: '/cards'
      fullPath: '/decks/$deckId/cards'
      preLoaderRoute: typeof DecksDeckIdCardsRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
  }
}

interface AlgorithmsRouteChildren {
  AlgorithmsAlgorithmIdRoute: typeof AlgorithmsAlgorithmIdRoute
}

const AlgorithmsRouteChildren: AlgorithmsRouteChildren = {
  AlgorithmsAlgorithmIdRoute: AlgorithmsAlgorithmIdRoute,
}

const AlgorithmsRouteWithChildren = AlgorithmsRoute._addFileChildren(
  AlgorithmsRouteChildren,
)

interface DecksDeckIdRouteChildren {
  DecksDeckIdCardsRoute: typeof DecksDeckIdCardsRoute
  DecksDeckIdDetailsRoute: typeof DecksDeckIdDetailsRoute
}

const DecksDeckIdRouteChildren: DecksDeckIdRouteChildren = {
  DecksDeckIdCardsRoute: DecksDeckIdCardsRoute,
  DecksDeckIdDetailsRoute: DecksDeckIdDetailsRoute,
}

const DecksDeckIdRouteWithChildren = DecksDeckIdRoute._addFileChildren(
  DecksDeckIdRouteChildren,
)

interface DecksRouteChildren {
  DecksDeckIdRoute: typeof DecksDeckIdRouteWithChildren
}

const DecksRouteChildren: DecksRouteChildren = {
  DecksDeckIdRoute: DecksDeckIdRouteWithChildren,
}

const DecksRouteWithChildren = DecksRoute._addFileChildren(DecksRouteChildren)

interface SettingsRouteChildren {
  SettingsInterfaceRoute: typeof SettingsInterfaceRoute
  SettingsLearningRoute: typeof SettingsLearningRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsInterfaceRoute: SettingsInterfaceRoute,
  SettingsLearningRoute: SettingsLearningRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

interface RouteChildren {
  AlgorithmsRoute: typeof AlgorithmsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DecksRoute: typeof DecksRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  TemplatesRoute: typeof TemplatesRouteWithChildren
}

const RouteChildren: RouteChildren = {
  AlgorithmsRoute: AlgorithmsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DecksRoute: DecksRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  TemplatesRoute: TemplatesRouteWithChildren,
}

const RouteWithChildren = Route._addFileChildren(RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Route: RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
