[package]
name = "koloda-core"
version = "0.0.1"
edition = "2021"
rust-version = "1.81.0"

[lints]
workspace = true

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
refinery = { version = "0.8", features = ["rusqlite"] }
rusqlite = { version = "0.33", features = ["bundled"] }
json-patch = "4.0"
strum = "0.27"
strum_macros = "0.27"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4"] }

[target.'cfg(not(windows))'.dependencies]
keyring = "3"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Security_Credentials"] }
