import type { Queries } from "@koloda/react";
import type {
  CloneAlgorithmData,
  CloneTemplateData,
  DB,
  DeleteAlgorithmData,
  DeleteCardData,
  DeleteDeckData,
  DeleteTemplateData,
  GetCardsCountParams,
  GetCardsParams,
  GetLessonDataParams,
  GetReviewsData,
  InsertAlgorithmData,
  InsertCardData,
  InsertDeckData,
  InsertReviewData,
  InsertTemplateData,
  LessonFilters,
  LessonResultData,
  PatchSettingsData,
  ResetCardProgressData,
  SetSettingsData,
  SettingsName,
  Template,
  UpdateAlgorithmData,
  UpdateCardData,
  UpdateDeckData,
  UpdateTemplateData,
} from "@koloda/srs";
import {
  addAlgorithm,
  addCard,
  addDeck,
  addReview,
  addTemplate,
  cloneAlgorithm,
  cloneTemplate,
  deleteAlgorithm,
  deleteCard,
  deleteDeck,
  deleteTemplate,
  getAlgorithm,
  getAlgorithmDecks,
  getAlgorithms,
  getCards,
  getCardsCount,
  getDeck,
  getDecks,
  getLessonData,
  getLessons,
  getReviews,
  getSettings,
  getTemplate,
  getTemplateDecks,
  getTemplates,
  getTodaysReviewTotals,
  patchSettings,
  resetCardProgress,
  setSettings,
  submitLessonResult,
  updateAlgorithm,
  updateCard,
  updateDeck,
  updateTemplate,
} from "@koloda/srs";
import { getStatus, setupFromScratch } from "./setup";

export const demoAppQueryOptions = {
  queryKey: ["app"],
  queryFn: getStatus,
  refetchOnReconnect: false,
  refetchOnWindowFocus: false,
  staleTime: Infinity,
};

export const demoSetupMutationOptions = { mutationFn: setupFromScratch };

export const queriesFn = (db: DB): Queries => ({
  getSettingsQuery: <T extends SettingsName>(name: T) => ({ queryFn: () => getSettings<T>(db, name) }),
  setSettingsMutation: <T extends SettingsName>() => ({
    mutationFn: (data: SetSettingsData<T>) => setSettings<T>(db, data),
  }),
  patchSettingsMutation: <T extends SettingsName>() => ({
    mutationFn: (data: PatchSettingsData<T>) => patchSettings<T>(db, data),
  }),
  getAlgorithmsQuery: () => ({ queryFn: () => getAlgorithms(db) }),
  getAlgorithmQuery: (id: string) => ({ queryFn: () => getAlgorithm(db, id) }),
  addAlgorithmMutation: () => ({ mutationFn: (data: InsertAlgorithmData) => addAlgorithm(db, data) }),
  cloneAlgorithmMutation: () => ({ mutationFn: (data: CloneAlgorithmData) => cloneAlgorithm(db, data) }),
  updateAlgorithmMutation: () => ({ mutationFn: (data: UpdateAlgorithmData) => updateAlgorithm(db, data) }),
  deleteAlgorithmMutation: () => ({ mutationFn: (data: DeleteAlgorithmData) => deleteAlgorithm(db, data) }),
  getAlgorithmDecksQuery: (id: string) => ({ queryFn: () => getAlgorithmDecks(db, id) }),
  getDecksQuery: () => ({ queryFn: () => getDecks(db) }),
  getDeckQuery: (id: string) => ({ queryFn: () => getDeck(db, id) }),
  addDeckMutation: () => ({ mutationFn: (data: InsertDeckData) => addDeck(db, data) }),
  updateDeckMutation: () => ({ mutationFn: (data: UpdateDeckData) => updateDeck(db, data) }),
  deleteDeckMutation: () => ({ mutationFn: (data: DeleteDeckData) => deleteDeck(db, data) }),
  getTemplatesQuery: () => ({ queryFn: () => getTemplates(db) }),
  getTemplateQuery: (id: Template["id"] | string) => ({ queryFn: () => getTemplate(db, id) }),
  addTemplateMutation: () => ({ mutationFn: (data: InsertTemplateData) => addTemplate(db, data) }),
  cloneTemplateMutation: () => ({ mutationFn: (data: CloneTemplateData) => cloneTemplate(db, data) }),
  updateTemplateMutation: () => ({ mutationFn: (data: UpdateTemplateData) => updateTemplate(db, data) }),
  deleteTemplateMutation: () => ({ mutationFn: (data: DeleteTemplateData) => deleteTemplate(db, data) }),
  getTemplateDecksQuery: (data: DeleteDeckData) => ({ queryFn: () => getTemplateDecks(db, data) }),
  getCardsQuery: (params: GetCardsParams) => ({ queryFn: () => getCards(db, params) }),
  getCardsCountQuery: (params: GetCardsCountParams) => ({ queryFn: () => getCardsCount(db, params) }),
  addCardMutation: () => ({ mutationFn: (data: InsertCardData) => addCard(db, data) }),
  updateCardMutation: () => ({ mutationFn: (data: UpdateCardData) => updateCard(db, data) }),
  deleteCardMutation: () => ({ mutationFn: (data: DeleteCardData) => deleteCard(db, data) }),
  resetCardProgressMutation: () => ({ mutationFn: (data: ResetCardProgressData) => resetCardProgress(db, data) }),
  getLessonsQuery: (filters?: LessonFilters) => ({ queryFn: () => getLessons(db, new Date(), filters) }),
  getTodayReviewTotalsQuery: () => ({ queryFn: () => getTodaysReviewTotals(db) }),
  getLessonDataQuery: ({ filters, amounts }: GetLessonDataParams) => ({
    queryFn: () => getLessonData(db, new Date(), filters, amounts),
  }),
  submitLessonResultMutation: () => ({ mutationFn: (data: LessonResultData) => submitLessonResult(db, data) }),
  getReviewsQuery: (data: GetReviewsData) => ({ queryFn: () => getReviews(db, data) }),
  addReviewMutation: () => ({ mutationFn: (data: InsertReviewData) => addReview(db, data) }),
});
